/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wievhaxedotrhktkjupg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpZXZoYXhlZG90cmhrdGtqdXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNTQ5NDYsImV4cCI6MjA3OTczMDk0Nn0.HVRvaWulgF-qWIHL2yQ4Wcwk-7SufNYgVb97STj_9Ok"